---
mainfont: LiberationSerif
sansfont: LiberationSans
monofont: LiberationMono
output: 
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: "preamble.tex"
  html_document:
    theme: readable
geometry: top=0cm,bottom=0cm,left=3cm
urlcolor: blue
---

```{r setup, include=FALSE}
library(pictoralist)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load the source code for the figure of card A
card_env_A <- new.env()
source(file='fig_comp_line.R', local=card_env_A)

# Load the source code for the figure of card B
card_env_B <- new.env()
source(file='fig_comp_bar.R', local=card_env_B)

# Load data and define recipient
data <- pictoralist::read_data('synth_data.csv')
recipient <- 'p9'
```

<!-- CARD 10A -->
\vspace{2.0cm}\ 

**Card 10A**

Dear Alex,

Your performance is consistently high for the measure [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03):

```{r figureA, echo=FALSE, fig.align='center', fig.width=4, fig.height=2.5, fig.showtext=TRUE}
  # Run figure generation
  card_env_A$run(recipient, data, "Goal")
```

\signoff
  
\vspace{2.5cm} 
...
\vspace{1.0cm} 

<!-- CARD 10B -->
**Card 10B**

Dear Alex,

Your performance is consistently high for the measure [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03):

```{r figureB, echo=FALSE, fig.align='center', fig.width=4, fig.height=2.5, fig.showtext=TRUE}
  # Run figure generation
  card_env_B$run(recipient, data, "Goal")
```

\signoff
