---
title: "card 14"
author: "DISPLAY Lab"
date: "2020-03-23"
mainfont: LiberationSerif
sansfont: LiberationSans
monofont: LiberationMono
output: 
  pdf_document:
    latex_engine: xelatex
  html_document:
    theme: readable
---

```{r setup, include=FALSE}
library(pictoralist)
knitr::opts_chunk$set(echo = TRUE)

# Load the source code for the figure
card_env <- new.env()
source(file='fig_single_bar.R', local=card_env)

# Load data and define recipient
data <- pictoralist::read_data('synth_data.csv')
recipient <- 'p13'
```

**To:** Shah, Nirav <nirshah@med.umich.edu>

**From:** mpog-quality@med.umich.edu

**Subject:** Your performance has not improved for PONV 03

\  
\  

Dear Dr. Shaw,

Your performance has not improved toward the goal for the measure of [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03):

\ 

```{r figuregen, echo=FALSE, fig.align='center', fig.width=5, fig.height=3, fig.showtext=TRUE}
  # Run figure generation
  card_env$run(recipient, data, list())
```

\  

Sincerely,

The MPOG Quality Team
