---
mainfont: LiberationSerif
sansfont: LiberationSans
monofont: LiberationMono
output: 
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: "preamble.tex"
  html_document:
    theme: readable
geometry: top=0cm,bottom=0cm,left=3cm
urlcolor: blue
---

```{r setup, include=FALSE}
library(pictoralist)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)


# Load the source code for the figure of card A
card_env_A <- new.env()
source(file='fig_one_bar.R', local=card_env_A)

# No figure for card B

# Load data and define recipient
# Use same performer as card 2
data <- pictoralist::read_data('synth_data.csv')
recipient <- 'p9'
goal_rate <- 0.90

# get most recent performance of performer
filter <- data$id == recipient & data$time == max(data$time)
numerator <- data[filter,'numer'][[1]]
denominator <- data[filter,'denom'][[1]]
# Scale goal to observed denominator.  Truncate to single decimal place
goal_percent <- paste(100*goal_rate, "%", sep="")
scaled_goal <- round(denominator*goal_rate, 1)
```

<!-- CARD 12A -->
\vspace{2.0cm}\ 

**Card 12A**

Dear Alex,

Congratulations on your high performance for the measure [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03):
```{r figureA, fig.align='center', fig.width=4, fig.height=2.5, fig.showtext=TRUE}
  # Run figure generation
  card_env_A$run(recipient, data, "GOAL")
```

\signoff
  
\vspace{2.5cm} 
...
\vspace{1.0cm} 

<!-- CARD 12B -->
**Card 12B**

Dear Alex,

Congratulations on your high performance for the measure, [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03), `r numerator`/`r denominator`, which was above the goal of 90% (`r scaled_goal`/`r denominator`).

\signoff
