---
mainfont: LiberationSerif
sansfont: LiberationSans
monofont: LiberationMono
output: 
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: "preamble.tex"
  html_document:
    theme: readable
geometry: top=2cm,bottom=1cm,left=3cm
---

```{r setup, include=FALSE}
library(pictoralist)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Load the source code for the figure of card A
card_env_A <- new.env()
source(file='fig_comp_line.R', local=card_env_A)

# Load the source code for the figure of card B
card_env_B <- new.env()
source(file='fig_comp_line.R', local=card_env_B)

# Load data and define recipient (Use same performer as card 2)
data <- pictoralist::read_data('synth_data.csv')
recipient <- 'p2'
```

<!-- CARD A -->
**Card A**
\  

Dear Dr. Shaw,

You are performing above the peer average for the measure of [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03):

```{r figureA, echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.width=5, fig.height=5, fig.showtext=TRUE}
  # Run figure generation
  card_env_A$run(recipient, data, list())
```

\  

Sincerely,

The MPOG Quality Team
  
\vspace{1.0cm}\ 
...
\vspace{1.0cm}\ 

<!-- CARD B -->
**Card B**
\  

Dear Dr. Shaw,

You are performing above the peer average for the measure of [postoperative nausea and vomiting](https://mpog.org/files/quality/measures/ponv-03_spec.pdf) (PONV 03):

```{r figureB, echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.width=5, fig.height=5, fig.showtext=TRUE}
  # Run figure generation
  card_env_A$run(recipient, data, list())
```

\  

Sincerely,

The MPOG Quality Team
